---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: instavote
  namespace: instavote
spec:
  events:
  - ping
  - push
  interval: 10m0s
  resources:
  - kind: GitRepository
    name: instavote
  secretRef:
    name: webhook-token
  type: github
